format = """
$username\
$hostname\
$directory\
${custom.jj}\
$cmd_duration\
${custom.current_task}\
$line_break\
$character"""

[directory]
style = "blue"

[character]
success_symbol = "[INSERT](cyan)"
error_symbol = "[ERROR](red)"
vimcmd_symbol = "[NORMAL](green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv@$version]($style) "
style = "bright-black"

[custom.jj]
when = "/home/ioane/.cargo/bin/jj-starship detect"
shell = ["/home/ioane/.cargo/bin/jj-starship"]
format = "$output "

[custom.current_task]
when = "test -f $HOME/.current_task"
command = "cat $HOME/.current_task | head -n 1"
format = "📝 $output "
