local lush = require('lush')
local hsl = lush.hsl

local darkness = hsl("#000000")
local comfort_ivory = hsl("#F8F7E2")
local blood = hsl("#bb0a1e")

-- autogenerated lush spec on 2021 წლის 28 ნოემბერი, 23:48:06
-- Run :Lushify
-- then /Normal to find the Normal group and edit your fg & bg colors
local lush = require("lush")
local hsl = lush.hsl
local hsluv = lush.hsluv

local melange = require("melange")
-- melange.Normal.bg = "black"

local theme = lush(melange)


return theme
